// Generated by LiveScript 1.2.0
/* expose a subset of an object */
(function(){
  module.exports = function(keys, obj){
    var proxy, this$ = this;
    proxy = {};
    keys.forEach(function(key){
      return Object.defineProperty(proxy, key, {
        get: function(){
          return deepGet(obj, key);
        },
        set: function(val){
          return deepSet(obj, key, val);
        },
        enumerable: true
      });
    });
    return proxy;
  };
  /* helper methods */
  function deepGet(obj, key){
    return deepGetArr(obj, key.split('.'));
  }
  function deepGetArr(obj, keyArr){
    var key;
    key = keyArr.shift();
    switch (keyArr.length) {
    case 0:
      return obj[key];
    default:
      return deepGetArr(obj[key], keyArr);
    }
  }
  function deepSet(obj, key, val){
    return deepSetArr(obj, key.split('.'), val);
  }
  function deepSetArr(obj, keyArr, val){
    var key;
    key = keyArr.pop();
    return deepGetArr(obj, keyArr)[key] = val;
  }
}).call(this);
